### ISSUE TITLE
Development <-> Production Environment

### ISSUE THREAD

**Issue by RuslanZavacky** [EwanValentine/SymfonyAngularDocker#8]
Hey @EwanValentine, pretty nice article, I have question regarding production environments.

1. Are you using the same setup as you've described for the production environments?
2. How you are doing deployments?
3. What if you need to deploy only frontend or only backend?
4. Howto update containers separately for example, redis or elasticsearch?

Thanks!

**Comment by EwanValentine** [comment]
Hi @RuslanZavacky,

Thanks for your questions :)

1. Not currently, we currently have a monolith stack. I was tasked with looking into how we could utilise a microservice approach. And, of course Docker was my starting point. 

2. We're still not too sure yet. But the way I've seen others do it, and this is probably the approach we'll take. You set up a server running Core OS, install Docker and docker-compose onto your Core OS server. Then run your containers on this new Core OS server. You could then use standard deployment tools such as Bamboo or Capistrano to ssh into your Core OS server and git pull on the appropriate volumes for example. 

3. Well I think this would be easier still with Docker. For instance, in this example each code base is in its own container. So you'd have a build script for each project, and it would pull the latest code into that volume. You wouldn't even need to touch Docker. But if you did, you could also control Docker from your build scripts.

Unless you meant re-deploying/building your containers? They could be version controlled and a part of your build scripts also. You could re-build the webserver container on deployment for example. Or do a fresh ``$ docker-compose build ``` each deployment? 

I don't think there's necessarily a best practice at this point, so have a play about and see what works best for you.

4. How do you mean by update? Update them to different versions of Redis for example? Or do you mean, how would you use Redis, Elasticsearch etc directly? 

Hope this helps!

Cheers,

Ewan

**Comment by RuslanZavacky** [comment]
2. This is a high level. But if you go a bit deeper, for example: When you deploy Symfony, you have to install vendors, rebuild cache. So you probably will do it in another folder, then you will switch symlinks (that's in normal way, without docker). With docker, there is a way like you build new container with new version of you Symfony code and ship it directly. Then you have to somehow "switch" containers one should go down, another up. And you can't just turn off one and enable another, as there will be a downtime and drop of connections. If you have a nginx+php container than you just rebuild one container. If you have separate nginx and separate php container, then code of Symfony API should be attached to both containers, that mean that you have to re-run 2 containers at the same time.

4. Yea, I mean upgrading Redis or ElasticSearch. As I've understand in you did not separate ElasticSearch and its volume from each other. So the data for ElasticSearch will be stored in the container itself. And if you need to upgrade it, then you'll be in trouble. 

I am asking, because I somehow haven't seen a good examples on how to use data-only volumes with services like ElasticSearch and best practices for them to be used.
